import type { PortalData } from "./portal-types";

export const PORTAL_SEEDS: Record<string, PortalData> = {
  "pets-delight": {
    clientId: "pets-delight",
    clientName: "Pets Delight",
    logoUrl: "/logo-pets-delight.jpg",
    agencyWhatsApp: "+971 52 256 0115",
    monthlyVideoQuota: 18,
    package: {
      name: "Full Social Media Management",
      services: [
        "18 short-form videos/month (scripting, shooting, editing, delivery)",
        "8 LinkedIn posts/month",
        "15 stories/month",
        "Community management",
        "Full social media management",
        "No on-camera client requirement",
      ],
      retainerAED: 5500,
      startDate: "2026-03-01",
      contractMonths: 3,
      primaryContactName: "Awab Sirelkhatim",
      primaryContactWhatsApp: "+971 52 256 0115",
      primaryContactEmail: "awab.sirelkhatim@gmail.com",
    },
    contentItems: [
      {
        id: "pd-may-1",
        month: "2026-05",
        number: 1,
        title: "Why Your Pet Deserves Premium Food",
        type: "Reel",
        ideaDescription: "Hook: 'Most pet food is just marketing.' We reveal what premium ingredients actually look like vs. cheap alternatives — positioned as an eye-opener. CTA: shop at Pets Delight. Voiceover-led, no on-camera required.",
        status: "posted",
        videoUrl: "",
        postedUrl: "https://www.instagram.com/p/example1",
        createdAt: "2026-05-01T09:00:00Z",
        updatedAt: "2026-05-10T14:00:00Z",
      },
      {
        id: "pd-may-2",
        month: "2026-05",
        number: 2,
        title: "Summer Pet Care Checklist",
        type: "Reel",
        ideaDescription: "Dubai summer heat hits 45°C — 5 things every Dubai pet owner needs to know to keep their pet safe. Fast cuts, bold text overlays, ends with 'visit Pets Delight for everything on this list.'",
        status: "posted",
        postedUrl: "https://www.instagram.com/p/example2",
        createdAt: "2026-05-01T09:00:00Z",
        updatedAt: "2026-05-12T10:00:00Z",
      },
      {
        id: "pd-may-3",
        month: "2026-05",
        number: 3,
        title: "What We Feed Our Cats Matters More Than You Think",
        type: "Reel",
        ideaDescription: "Educational angle: breakdown of cat nutrition labels. Show a 'bad' label vs. a 'good' label side by side. Ends with Pets Delight cat food range. Voiceover + text overlays.",
        status: "client_approved",
        createdAt: "2026-05-01T09:00:00Z",
        updatedAt: "2026-05-13T16:00:00Z",
      },
      {
        id: "pd-may-4",
        month: "2026-05",
        number: 4,
        title: "Dog Grooming Before & After",
        type: "Reel",
        ideaDescription: "Before/after transformation of a dog getting groomed. Before: messy, shaggy. After: clean, trimmed. Show the Pets Delight grooming products used. Satisfying cut transitions with upbeat background audio.",
        status: "ready_for_review",
        videoUrl: "https://drive.google.com/file/d/example-video-link/view",
        createdAt: "2026-05-01T09:00:00Z",
        updatedAt: "2026-05-14T11:00:00Z",
      },
      {
        id: "pd-may-5",
        month: "2026-05",
        number: 5,
        title: "3 Signs Your Dog is Overheating",
        type: "Reel",
        ideaDescription: "Urgent, health-first angle. 3 warning signs Dubai dog owners miss. Short, punchy, 20 seconds. Ends with 'Pets Delight has everything to keep them cool this summer.' Text overlays only — no voiceover.",
        status: "in_production",
        createdAt: "2026-05-05T10:00:00Z",
        updatedAt: "2026-05-14T09:00:00Z",
      },
      {
        id: "pd-may-6",
        month: "2026-05",
        number: 6,
        title: "A Day in the Life of a Pets Delight Customer",
        type: "Reel",
        ideaDescription: "Day-in-the-life format: morning feeding routine, afternoon walk, evening playtime — all featuring Pets Delight products. Relatable, warm, lifestyle-focused. No hard sell. Soft CTA: 'Make every moment count.'",
        status: "in_production",
        createdAt: "2026-05-05T10:00:00Z",
        updatedAt: "2026-05-14T09:00:00Z",
      },
      {
        id: "pd-may-7",
        month: "2026-05",
        number: 7,
        title: "The Fish Tank Setup Guide",
        type: "Reel",
        ideaDescription: "Step-by-step how to set up a beginner fish tank using Pets Delight aquarium supplies. Satisfying time-lapse cuts, clean aesthetic. Great for saves. 'Everything you need is at Pets Delight.'",
        status: "idea_approved",
        createdAt: "2026-05-07T08:00:00Z",
        updatedAt: "2026-05-12T10:00:00Z",
      },
      {
        id: "pd-may-8",
        month: "2026-05",
        number: 8,
        title: "Rabbit Care 101",
        type: "Reel",
        ideaDescription: "Under-served niche in UAE: rabbit owners. '5 things every rabbit owner in Dubai needs to know.' Positions Pets Delight as the expert source for small pet care. Text overlays, calm tone.",
        status: "idea_approved",
        createdAt: "2026-05-07T08:00:00Z",
        updatedAt: "2026-05-13T09:00:00Z",
      },
      {
        id: "pd-may-9",
        month: "2026-05",
        number: 9,
        title: "Why We Don't Compromise on Pet Health",
        type: "Reel",
        ideaDescription: "Brand story angle: Pets Delight origin story, why quality matters to them, what they won't stock vs. what they will. Emotional, trust-building. Could use a voiceover from Marwan if available, or text-led.",
        status: "idea_pending",
        createdAt: "2026-05-10T09:00:00Z",
        updatedAt: "2026-05-10T09:00:00Z",
      },
      {
        id: "pd-may-10",
        month: "2026-05",
        number: 10,
        title: "Cat vs. Dog Food: What's the Difference?",
        type: "Reel",
        ideaDescription: "Educational myth-buster. A lot of UAE pet owners don't know cats and dogs need completely different nutrition. Punchy, scroll-stopper format. Text overlays, side-by-side comparisons.",
        status: "idea_pending",
        createdAt: "2026-05-10T09:00:00Z",
        updatedAt: "2026-05-10T09:00:00Z",
      },
      {
        id: "pd-may-11",
        month: "2026-05",
        number: 11,
        title: "Pet Accessories That Actually Work",
        type: "Reel",
        ideaDescription: "Review-style: 3 accessories that look gimmicky but are genuinely useful, available at Pets Delight. Builds credibility and drives product discovery. Honest, no-hype tone.",
        status: "idea_pending",
        createdAt: "2026-05-10T09:00:00Z",
        updatedAt: "2026-05-10T09:00:00Z",
      },
      {
        id: "pd-may-12",
        month: "2026-05",
        number: 12,
        title: "New Arrivals This Month",
        type: "Story",
        ideaDescription: "Product showcase story series: swipe through new arrivals at Pets Delight this month. Clean product shots, price tags, 'Available now' CTA. Quick to produce, high commercial value.",
        status: "idea_pending",
        createdAt: "2026-05-10T09:00:00Z",
        updatedAt: "2026-05-10T09:00:00Z",
      },
    ],
    analytics: [
      {
        id: "pd-analytics-1",
        weekDate: "2026-04-28",
        instagram: {
          followers: 3910,
          followersChange: 65,
          views: 38200,
          reach: 22100,
          engagementRate: 3.8,
        },
        notes: "Strong week — Summer Pet Care Checklist performed well.",
        enteredAt: "2026-05-05T10:00:00Z",
      },
      {
        id: "pd-analytics-2",
        weekDate: "2026-05-05",
        instagram: {
          followers: 4010,
          followersChange: 100,
          views: 44600,
          reach: 29300,
          engagementRate: 4.1,
          topPostUrl: "https://www.instagram.com/p/example1",
        },
        notes: "Best week yet. Premium food video hit 18K views organic.",
        enteredAt: "2026-05-12T09:00:00Z",
      },
      {
        id: "pd-analytics-3",
        weekDate: "2026-05-12",
        instagram: {
          followers: 4148,
          followersChange: 138,
          views: 51200,
          reach: 33800,
          engagementRate: 4.4,
          topPostUrl: "https://www.instagram.com/p/example2",
        },
        notes: "Followers growing fast. Community management engagement up. Grooming B&A video ready for client review.",
        enteredAt: "2026-05-17T09:00:00Z",
      },
    ],
    invoices: [
      {
        id: "pd-inv-march",
        number: "PD/MAR/001",
        month: "March 2026",
        date: "2026-03-01",
        dueDate: "2026-03-05",
        amountAED: 5500,
        vatAED: 275,
        totalAED: 5775,
        status: "paid",
        paidDate: "2026-03-04",
      },
      {
        id: "pd-inv-april",
        number: "PD/APR/002",
        month: "April 2026",
        date: "2026-04-01",
        dueDate: "2026-04-05",
        amountAED: 5500,
        vatAED: 275,
        totalAED: 5775,
        status: "paid",
        paidDate: "2026-04-03",
      },
      {
        id: "pd-inv-may",
        number: "PD/MAY/003",
        month: "May 2026",
        date: "2026-05-01",
        dueDate: "2026-05-05",
        amountAED: 5500,
        vatAED: 275,
        totalAED: 5775,
        status: "paid",
        paidDate: "2026-05-04",
      },
    ],
    updatedAt: "2026-05-17T09:00:00Z",
  },

  "crystalline": {
    clientId: "crystalline",
    clientName: "Crystalline",
    logoUrl: "",
    agencyWhatsApp: "+971 52 256 0115",
    monthlyVideoQuota: 15,
    package: {
      name: "Full Social Media Management",
      services: [
        "15 short-form videos/month (scripting, shooting, editing, delivery)",
        "Full social media management",
        "Content strategy & planning",
        "No on-camera client requirement",
      ],
      retainerAED: 5500,
      startDate: "2026-05-18",
      contractMonths: 3,
      primaryContactName: "Awab Sirelkhatim",
      primaryContactWhatsApp: "+971 52 256 0115",
      primaryContactEmail: "awab.sirelkhatim@gmail.com",
    },
    contentItems: [
      {
        id: "cr-may-1",
        month: "2026-05",
        number: 1,
        title: "What Makes Aluminium & Glass the Future of Modern Design",
        type: "Reel",
        ideaDescription: "Brand introduction video. Showcase stunning Crystalline projects — facades, windows, glass partitions. Position Crystalline as the premium choice for modern architecture in the UAE. Bold visuals, no voiceover needed — music and text overlays only.",
        status: "idea_pending",
        createdAt: "2026-05-17T10:00:00Z",
        updatedAt: "2026-05-17T10:00:00Z",
      },
      {
        id: "cr-may-2",
        month: "2026-05",
        number: 2,
        title: "Before & After: Office Transformation with Glass Partitions",
        type: "Reel",
        ideaDescription: "Before/after transformation of a commercial space. Dramatic reveal moment. Shows the impact Crystalline products have on a space. Great for saves and shares. Perfect first social proof content.",
        status: "idea_pending",
        createdAt: "2026-05-17T10:00:00Z",
        updatedAt: "2026-05-17T10:00:00Z",
      },
      {
        id: "cr-may-3",
        month: "2026-05",
        number: 3,
        title: "Why Architects in Dubai Choose Crystalline",
        type: "Reel",
        ideaDescription: "Trust-building content for B2B audience. '3 reasons Dubai's top architects specify our aluminium systems.' Positions Crystalline as the expert choice, not just the cheapest option. Professional tone, text-only, sleek aesthetic.",
        status: "idea_pending",
        createdAt: "2026-05-17T10:00:00Z",
        updatedAt: "2026-05-17T10:00:00Z",
      },
    ],
    analytics: [],
    invoices: [
      {
        id: "cr-inv-may",
        number: "CR/MAY/001",
        month: "May 2026",
        date: "2026-05-18",
        dueDate: "2026-05-22",
        amountAED: 2500,
        vatAED: 125,
        totalAED: 2625,
        status: "pending",
      },
    ],
    updatedAt: "2026-05-17T10:00:00Z",
  },
};
